10.3  异常
Python异常使用try-except代码块处理。try-except代码块让Python执行制定操作，同时告诉Python发生异常是怎么做。
使用try-except代码块是，即使出现异常，程序也可以继续运行：显示自己编写的友好错误提示信息，而不是traceback。

10.3.1 处理ZeroDivisionError异常'
division.py

print(5/0)
报错：
Traceback (most recent call last):
File "division.py", line 1, in <module>
print(5/0)
 ZeroDivisionError: division by zero
 我们可以使用try-except告诉Python发生这种错误时该怎么办。
 
 10.3.2 使用try-except
 try-except的使用方式：类似java中的try-catch
 try:
     print(5/0)
 except ZeroDivisionError:
     print("You can't divide by zero")
这样如果try中的代码运行没有问题，将跳过except代码块；如果有问题，若except指定的错误和
引发的错误相同，就会运行except代码块。

10.3.3  使用异常避免崩溃

发生错误时，如果程序还有工作没有完成，妥善的处理错误尤其重要
