# 10.3  异常

Python异常使用try-except代码块处理。try-except代码块让Python执行制定操作，同时告诉Python发生异常是怎么做。
使用try-except代码块是，即使出现异常，程序也可以继续运行：显示自己编写的友好错误提示信息，而不是traceback。

### 10.3.1 处理ZeroDivisionError异常

division.py

print(5/0)
报错：
Traceback (most recent call last):
File "division.py", line 1, in <module>
print(5/0)
 ZeroDivisionError: division by zero
 我们可以使用try-except告诉Python发生这种错误时该怎么办。

### 10.3.2 使用try-except

try-except的使用方式：类似java中的try-catch
try:
    print(5/0)
except ZeroDivisionError:
    print("You can't divide by zero")
这样如果try中的代码运行没有问题，将跳过except代码块；如果有问题，若except指定的错误和
引发的错误相同，就会运行except代码块。

### 10.3.3  使用异常避免崩溃

发生错误时，如果程序还有工作没有完成，妥善的处理错误尤其重要。这种情况经常出现在要求用户提供输入的程序中；如果程序能够妥善处理无效输入，就能再提示用户提供有效输入，而不至于崩溃。
一个简单的除法计算器：  
division.py  
```
print ("Give me two numbers, and I'll divide them.")  
print("Enter 'q' to quit.")  

while True:
    first_number = input("\nFirst number: ")  
    if first_number == 'q':  
        break  
    second_number = input("\nSecond number: ")  
    if second_number == 'q':  
        break  
    answer = int(first_number) / int(second_number)
    print(answer)
```     
这个程序没有进行错误处理，除数为0时将崩溃：  

### 10.3.4 else代码块
将可能引发错误的代码放在try-except代码块中；依赖于try代码块成功执行的代码放到else代码块中： 

```
print ("Give me two numbers, and I'll divide them.")  
print("Enter 'q' to quit.")  

while True:
   first_number = input("\nFirst number: ")  
   if first_number == 'q':  
       break  
   second_number = input("\nSecond number: ")  
   if second_number == 'q':  
       break  
   try:
       answer = int(first_number) / int(second_number)
   except Z:
   print(answer)
 ```
### 10.3.5 处理FileNotFoundError
尝试读取一个不存在的文件：  
alice.py
```
filename = 'alice.txt'

with open(filename) as f_obj:
    contents = f_obj.read()

filename = 'alice.txt'
try:
    with open(filename) as f_obj:
        contents = f_obj.read()
except FileNotFoundError:
    msg = "Sorry, the file " + filename + " does not exist."
    print(msg)
```
都是采用try-except的处理方式。  
### 10.3.6 分析文本
分析小说中多少个单词：split()以空格为分隔符将字符串分拆成多个部分存储在列表中。

```
filename = 'alice.txt'
try:
    with open(filename) as f_obj:
        contents = f_obj.read()
except FileNotFoundError:
    msg = "Sorry, the file " + filename + " does not exist."
    print(msg)
else:
    words = contents.split()
    num_words = len(words)
    print("The file " + filename + "has about " +         str(num_words) + " wrods.")
```

### 10.3.7使用多个文件   
```
filenames = ['alice.txt','little.txt']
for filename in filenames:
    count_words(filename)
```
### 10.3.8  使用pass  
```
def count_words(filename):
    try:
        --snip--
    except FileNotFoundError:
        pass
    else:
        --snip--
```
这个程序异常时什么都不做  

# 10.4 存储数据
### 10.4.1 使用json.dump()存储数据，json.load()加载数据
number_writer.py
```
import json

numbers = [3,4,2,5,55,23]

filename = 'numbers.json'
with open(filename, 'w') as f_obj:
   json.dump(numbers, f_obj)
```
number_reader.py

```
import json

filename = 'numbers.json'
with open(filename) as f_obj:
    numbers = json.load(f_obj)

print(numbers)
```

